---
- name: influxdb_installation_Debian | Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  when: influxdb_manage_repository

- name: influxdb_installation_Debian | Add Influxdb repository key
  ansible.builtin.apt_key:
    url: "{{ influxdb_apt_key }}"
    state: present
  when: influxdb_manage_repository and influxdb_apt_key

- name: influxdb_installation_Debian | Add InfluxDB repository
  ansible.builtin.apt_repository:
    repo: "{{ influxdb_apt_url }}"
    state: present
    mode: 0644
  when: influxdb_manage_repository

- name: influxdb_installation_Debian | Ensure InfluxDB is installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  when: influxdb_manage_package
  notify: Start-influxdb
  loop:
    - influxdb

# TODO: Find a better way to improve this feature
# - name: Debian - Ensure python influxdb library
#   pip:
#     name: influxdb
