---
- name: influxdb_installation_RedHat | Add InfluxDB repository
  ansible.builtin.yum_repository:
    name: InfluxDB
    description: InfluxDB Repository - RHEL \$releasever
    baseurl: "{{ influxdb_yum_url }}"
    gpgkey: "{{ influxdb_yum_key }}"
    gpgcheck: true
  when: influxdb_manage_repository

- name: influxdb_installation_RedHat | Ensure InfluxDB is installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  when: influxdb_manage_package
  notify: Start-influxdb
  loop:
    - influxdb

# TODO: Find a better way to improve this feature
# - name: RedHat - Ensure python influxdb library
#   pip:
#     name: influxdb
