---
- name: Start-influxdb
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true
    retries: 10
    delay: 5

- name: Restart-influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted
