---
- name: Prepare container
  hosts: all
  gather_facts: true
  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    # - role: buluma.buildtools
    # - role: buluma.ca_certificates

  tasks:
    - name: install python-pip on RHEL7
      ansible.builtin.yum:
        name: python-pip
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: install python3-pip on RHEL8
      ansible.builtin.yum:
        name: python3
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: apt install pip on Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - python3-pip
        - python3-setuptools
        - gnupg
        - build-essential
        - libjpeg-dev
        - libpng-dev
        - libtiff-dev
      when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )

    - name: install pip on Debian
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - gnupg
        - python-setuptools
        - python-pip
      when: ( ansible_os_family == "Debian" and ( ansible_distribution_major_version == "10" or ansible_distribution_major_version == "9" ))
